### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ComFreek** [jpaulm/jsfbp#16]
Some notes and findings:
<hr>

- [x] Split index.js into core components
- [x] Coding style:
  - [x] Replaced CRLF by LF
  - [x] Added 'use strict' to all core/component files. I've left out the examples for brevity.
  - [x] Gitignore old-node compatibility stuff, i.e. [the files I created to use an older Node.js version](https://gist.github.com/ComFreek/c341bacfaae3aca887df). Admittedly, I was annoyed by the untracked files which had been always listed by `git status`.
 - [x] Consistent braces
 - [x] Consistent semicolons
 - [ ] OutputPort, don't use magic status strings ==> emulate enums with JS
 - [ ] Remove global tracing variable
 - [x] Replace `new Array` by `[]`. @jpaulm They are the same commands, but the latter is more idiomatic.
 - [ ] index.js: The function run2 is definitely too long and too deeply nested.
- Bugs:
  - [ ] InputPortArray and OutputPortArray: escape regex
  - [ ] Potential bug: don't compare constructor to Utils.InitConn. This might get tricky if the object is coming from another frame (in the browser), so `Utils.InitConn (frame A) != Utils.InitConn (frame B)`!

**Comment by jpaulm** [comment]
@dancrumb - you might want to take a look at @comfreek's suggestions - or maybe you already have!
